### ISSUE TITLE
Singular matrix error

### ISSUE THREAD

**Issue by joshua-wx** [nasa/SingleDop#20]
Hi Tim,

Firstly, thanks for the fantastic implementation of the Xu et al. 2006 algorithm.
I'm testing your code on the Australian Doppler radar network for near real-time 2D wind retrieval (24 radars on 6 minute volumes).
It's working really well, and I'll be presenting a 9 year validation against surface data at the AMS radar conference... but I'm just having one nagging issue!
Some volumes return a singular matrix error

`Traceback (most recent call last):
  File "sd_winds_pltout.py", line 66, in <module>
    filter_data=True,filter_distance=5)
  File "build/bdist.linux-x86_64/egg/singledop/singledop.py", line 304, in __init__
  File "build/bdist.linux-x86_64/egg/singledop/singledop.py", line 484, in compute_single_doppler_retrieval
  File "/home/meso/anaconda2/lib/python2.7/site-packages/scipy/linalg/basic.py", line 103, in solve
    raise LinAlgError("singular matrix")
numpy.linalg.linalg.LinAlgError: singular matrix`

Australian Doppler radar data is a mess. We have dualPRF artifacts, the network is full of different models/makes and the data quality is low in general... so I apply despeckle and median filtering. Here's the script I call [link](https://www.dropbox.com/s/2uwb4jjouw0ybsq/sd_winds_pltout.py?dl=0) 
and a volume which crashes the script [link](https://www.dropbox.com/s/twr19b0sw8glh1x/66_20141127_062400.h5?dl=0)

Cheers!

**Comment by tjlang** [comment]
Thanks for letting me know about this. I will check out the dataset you link too, but at first glance I suspect that this is a data QC issue. Another possibility might be a memory issue - you could try downsampling the dataset (e.g., making range_spacing and az_spacing keywords larger values) on the problematic volumes.

**Comment by tjlang** [comment]
More info on singular matrix issues - http://stackoverflow.com/questions/10326015/singular-matrix-issue-with-numpy

**Comment by joshua-wx** [comment]
Thanks for the quick response Tim.
Changing the downsampling parameters has no effect on problematic volumes (and changing the range). I run everything on xlarge EC2 machines, so I don't think memory would be an issue (some recent sweeps have had >5000 elements and quickly process without an issue)

Any idea what sort of QC issue would produce this issue? I was hoping that my filtering would remove such problems.

**Comment by tjlang** [comment]
What is the Nyquist velocity of the sample volume?

**Comment by tjlang** [comment]
I've successfully reproduced the singular matrix error on the uncorrected data. Looks like something weird, could be a while before I can find the culprit.

Can you also post a successful volume?

Thanks,
Timothy

**Comment by joshua-wx** [comment]
Hi Tim,
The nyquist is 52.2m/s for that radar.
Here's a link to a volume from the same radar which works.
https://www.dropbox.com/s/l1zkea8gc5k19dp/66_20141106_064800.h5?dl=0

The issue appears to be more prevalent with historical data too... But both historical data and more recent data have been processed with the same utility set!

Cheers,
Joshua

**Comment by tjlang** [comment]
Thanks, I can confirm the successful volume works for me too. Now the real work begins. I am traveling this week, so please be patient.

**Comment by joshua-wx** [comment]
No problem Tim. Thanks for starting the investigation.

**Comment by tjlang** [comment]
The A matrix in the problem volume is not perfectly symmetric and positive definite. This causes a failure as the scipy.linalg.solve call is made with this assumption, to keep computation requirements low. In https://github.com/nasa/SingleDop/pull/21, I have added some exception handling in case the LinAlgError comes up. In that event, a second attempt is made without the sym_pos=True keyword. This seems to fix the problem for the sample volume provided. 

I think the matrix assumption violations are just numeric in origin, and not the result of some major data issue. 

![image](https://cloud.githubusercontent.com/assets/3036387/26312140/aa867c74-3ed4-11e7-8df1-bbb64fb37f43.png)

**Comment by joshua-wx** [comment]
Great, thank you for the quick fix!
If you make it to the AMS radar conference please let me know.

**Comment by tjlang** [comment]
Yes, I will be there. I am on the program committee.
