### ISSUE TITLE
Exporting derived wind field in ASCII/NETCDF

### ISSUE THREAD

**Issue by pandasambit15** [nasa/SingleDop#24]
Hi!
Is there any way of exporting the U,V fields along with the lat/lon grid to ASCII or NETCDF files?

**Comment by tjlang** [comment]
Yes, the NetcdfSave class will save lat, lon, and velocity vectors in netCDF. See the demo notebook for an example of how that works.

**Comment by pandasambit15** [comment]
Dear Timothy,

Thanks for your response.

I have checked the notebook and have used the method of NetcdfSave also for
saving the output. But, it saves the analysis_x and analysis_y variables
(cartesian distances in km I guess), rather than the Lat Lon grid. How can
we convert those to lat-lon values? Also, which projection (if any) is used
to calculate x and y?

*Sambit Kumar Panda*
*Scientist/Engineer-SD, ASD/AOSG/EPSA,*
*SAC(ISRO), Ahmedabad*

**Comment by tjlang** [comment]
Please see the common.py code, specifically the `radar_coords_to_cart` function. This function (stolen from Py-ART) does the coordinate transformation.
